name: Aaronfloyd
favicon: null
layout_spectrum: 0.8280060654506087
typography_spectrum: 0.28577008098363876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6090156526770443
  lightness: 0.30026365094818175
  saturation: 0.43059483729302883
  rhythmicContrast: 0.47610259079374373
purpose: []
